flyway.url=jdbc:sqlserver://sqlserver:1433;databaseName=master;encrypt=true;trustServerCertificate=true
flyway.user=sa
flyway.password=Gathel123!

flyway.locations=filesystem:/flyway/sql
flyway.defaultSchema=dbo
flyway.schemas=dbo

flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.outOfOrder=false